// PDF Export utility using browser's print functionality
// This generates a print-friendly page that can be saved as PDF

export interface PDFExportOptions {
  title: string;
  content: string;
  country?: string;
  currency?: string;
}

export function generatePDFContent(options: PDFExportOptions): string {
  const { title, content, country, currency } = options;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }

    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #3b82f6;
    }

    .header h1 {
      font-size: 24px;
      color: #1e40af;
      margin-bottom: 5px;
    }

    .header p {
      font-size: 14px;
      color: #64748b;
    }

    .meta {
      display: flex;
      justify-content: space-between;
      margin-bottom: 20px;
      padding: 10px;
      background: #f1f5f9;
      border-radius: 8px;
      font-size: 14px;
    }

    .meta span {
      color: #475569;
    }

    .content {
      margin-top: 20px;
    }

    .section {
      margin-bottom: 20px;
    }

    .section h2 {
      font-size: 18px;
      color: #1e293b;
      margin-bottom: 10px;
      padding-bottom: 5px;
      border-bottom: 1px solid #e2e8f0;
    }

    .row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #f1f5f9;
    }

    .row:last-child {
      border-bottom: none;
    }

    .label {
      color: #64748b;
    }

    .value {
      font-weight: 600;
      color: #0f172a;
    }

    .value.positive {
      color: #16a34a;
    }

    .value.negative {
      color: #dc2626;
    }

    .highlight {
      background: #eff6ff;
      padding: 15px;
      border-radius: 8px;
      text-align: center;
      margin: 20px 0;
    }

    .highlight .big {
      font-size: 28px;
      font-weight: 700;
      color: #1e40af;
    }

    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      font-size: 12px;
      color: #94a3b8;
    }

    .footer a {
      color: #3b82f6;
      text-decoration: none;
    }

    @media print {
      body {
        padding: 20px;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🇪🇺 ${title}</h1>
    <p>EU Tax Calculator - Tax Calculation Report</p>
  </div>

  <div class="meta">
    ${country ? `<span>Country: <strong>${country}</strong></span>` : ''}
    ${currency ? `<span>Currency: <strong>${currency}</strong></span>` : ''}
    <span>Date: <strong>${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</strong></span>
  </div>

  <div class="content">
    ${content}
  </div>

  <div class="footer">
    <p>Generated by <a href="https://eu-tax-calculator.vercel.app">EU Tax Calculator</a></p>
    <p>This document provides estimates based on publicly available tax rates and rules.</p>
    <p>For accurate tax advice, please consult a qualified tax professional.</p>
  </div>
</body>
</html>
  `;
}

export function exportToPDF(options: PDFExportOptions): void {
  const htmlContent = generatePDFContent(options);

  // Open a new window with the print-friendly content
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export as PDF');
    return;
  }

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  // Wait for content to load, then trigger print dialog
  printWindow.onload = () => {
    printWindow.print();
  };

  // Fallback: trigger print after a short delay if onload doesn't fire
  setTimeout(() => {
    if (!printWindow.closed) {
      printWindow.print();
    }
  }, 500);
}

export function formatCurrencyForPDF(amount: number, currency: string): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

export function formatPercentForPDF(rate: number): string {
  return `${(rate * 100).toFixed(1)}%`;
}